### ISSUE TITLE
Flatpak version outdated

### ISSUE THREAD

**Issue by Volken-x** [flathub/fr.free.Homebank#19] opened 2022-11-03 12:57 UTC
Hello guys,

the homebank app from the PPA is 5.5.8, the last uptade in flathub is version 5.5.5. The project is still running? Newer versions will be added to flathub repository?

**Comment by ahayzen** [comment] 2022-11-06 11:27
Duplicate of #18

**Closed** 2023-06-14 20:26 UTC
